# Generated by Django 4.1.4 on 2022-12-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.CharField(blank=True, max_length=2000, verbose_name='Comentario')),
                ('me_gusta', models.BooleanField(default=False)),
            ],
        ),
    ]
