# Generated by Django 4.1.4 on 2022-12-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noticia', '0001_initial'),
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='noticia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='noticia.noticia'),
        ),
    ]
